import userPic from "./assets/userPic.jpg";

export const userAppInfo = [
  {
    id: 1,
    image: userPic,
    assessment: "Intake Comprehensive Assessment",
    name: "Malenie Laurent",
    appId: 324424,
    taskId: 232323,
    date: "Thursday, 28 Dec 2022",
    appDate: "December 22, 2022 10:30 AM",
    duration: 1,
    status: "Overdue",
  },
  {
    id: 2,
    image: userPic,
    assessment: "Physiotherapy Assessment",
    name: "Malenie Laurent",
    appId: 324424,
    taskId: 232323,
    date: "Thursday, 27 Dec 2022",
    appDate: "December 22, 2022 10:30 AM",
    duration: 1,
    status: "Upcoming",
  },
  {
    id: 3,
    image: userPic,
    assessment: "Intake Comprehensive Assessment",
    name: "Malenie Laurent",
    appId: 324424,
    taskId: 232323,
    date: "Thursday, 27 Dec 2022",
    appDate: "December 22, 2022 10:30 AM",
    duration: 1,
    status: "Overdue",
  },
];
